### ISSUE TITLE
Add a testing framework

### ISSUE THREAD

**Issue by gaurav** [NCATS-Gamma/omnicorp#17]
Jim suggested [utest](https://github.com/lihaoyi/utest). As of PR #27, we have tests for both individual methods (`PubMedArticleWrapper.parseDate`) as well as the entire article parsing process (`PubMedArticleWrapper.asString`). I'll close this issue once we have some tests for the generation of triples as well.

**Comment by balhoff** [comment]
@gaurav I think this is done, right?

**Comment by gaurav** [comment]
We currently only test whether the right properties are being generated in the RDF output. In PR #32, I'm working on tests that actually checks that the right triples are being generated for some examples. I think we should close this issue once that PR has been completed and merged.
