### ISSUE TITLE
Export dates in triples

### ISSUE THREAD

**Issue by gaurav** [NCATS-Gamma/omnicorp#20]
We should export:
* [PubDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#pubdate) is the full date on which the issue of the journal was published.
* [DateCompleted](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#datecompleted) is the date on which processing of this record was completed and it was published to PubMed with MeSH Headings and quality assurance validations.
* [DateRevised](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#daterevised) is the date on which the last change was made to this record.

We might also want to export:
* [DateCreated](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#datecreated) has been deprecated, but used to be the date at which processing of this record began.
* [ArticleDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#articledate) is the date the publisher made an electronic version of the article available.
* [PubMedPubDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#pubmedpubdate) includes one or more dates significant to either the article's history or the citation's processing. We will have to do some processing to figure out which of these dates will be useful to us.
* [VersionDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#versiondate) attribute is used when publishers release multiple versions of the same article, sometimes in quick succession and sometimes almost as soon as the original article has been published. To associate versioned articles with each other, NLM creates an individual citation for each article’s version and links the versions via the VersionID and VersionDate attributes of <MedlineCitation> and the Version attribute in the <PMID> element. The VersionID and VersionDate values supplied by the publisher will identify the specific version. The VersionDate value may be the same as the citation’s <PubDate> if the new version was released later the same day that the article was first published.

**Comment by balhoff** [comment]
@cbizon should we just pick one of these to be "the date" in OmniCorp for a given PMID? @gaurav is `PubDate` available for at least nearly all the articles?

**Comment by cbizon** [comment]
I think so, if the coverage is there...

**Comment by gaurav** [comment]
I'll get some coverage numbers on PubDate and report back.

**Comment by gaurav** [comment]
I've [got numbers](https://gist.github.com/gaurav/cfbc0363af306bf7e4fd978f6ee7715c), thanks to the code in PR #22!

Out of 29,100,000 articles:
 - 26,982,921 articles (92.7%) have a [PubDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#pubdate).
 - 27,361,836 articles (94.0%) have [DateCompleted](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#datecompleted) fields.
 - All of them (100%) have [DateRevised](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#daterevised) fields.
 - 7,581,772 articles (26.1%) have [ArticleDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#articledate) fields.
 - All of them (100%) have [PubMedPubDate](https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#pubmedpubdate)'s for 'entrez', 'medline' and 'pubmed' (which I think are the dates at which these were added to those databases)
    - Some of them have other PubMedPubDates: 5,580,218 (19.2%) for "accepted", 5,735,919 (19.7%) for "received", and 2,758,808 (9.5%) for "revised". We have a few dates for "pmc-release", "aheadofprint" and "retracted" (3!).

So, I think we should use:
 - PubDate for the date of publication ([dct:issued](http://purl.org/dc/terms/issued))
 - DateRevised for the date of last modification ([dct:modified](http://purl.org/dc/terms/modified))
